config/routes.rb
Rails.application.routes.draw do

  root "alpha_blog#home"
  get "about",  to: "alpha_blog#about" 
resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title ,presence:true ,length: {minimum: 3,maximum: 50}
    validates :description ,presence:true,length: {minimum: 10,maximum: 300}
end

app/controllers/alpha_blog_controller.rb
class AlphaBlogController < ApplicationController
def home

end
def about

end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
def index
 @articles = Article.all
end
def new
    @article = Article.new
end
def edit
 @article = Article.find(params[:id])
end
 def create 
     #render plain: params[:article].inspect
     @article = Article.new(article_params)
    if @article.save
    flash[:notice]="Article was successfully created"    
     redirect_to article_path(@article) 
    else
     render 'new'
    end
 end
 
 def show
 @article = Article.find(params[:id])
 end 
 
 def destroy
 @article = Article.find(params[:id])
 @article.destroy
 flash[:notice] = "Article was successfully deleted"
 redirect_to articles_path
 end
 def update 
  @article = Article.find(params[:id])
 if @article.update(article_params)
 flash[:notice] = "Article was succefully updated"
 redirect_to article_path(@article)
else
 render 'edit'
 end
 end
end
private
 def article_params
     params.require(:article).permit(:title,:description)  
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alpha_blog/about.html.erb
<html>
<body>
<head>
<title> 
Home Work Assignment
</title>
</head>
<table width="100%"style ="height:100%;" cellpadding = "10" cellspacing="0" border ="0">
<tr>
<!-- Header Section-->
<td colspan ="2" style = "height: 100px; color:white"; bgcolor="black" align= "center"	><h1>Website Name </h1></td>
</tr>
<!-- Menu Section-->
<tr>
<td width = "20%" height = "100%" valign="top" bgcolor = "#808B96">
<b> HTML </b><br>
<b> CSS </b> 
 </td>
 <!-- Content Section -->
 <td width = "80%" height = "80%" valign="top" bgcolor = "white" align = "justify">
 <h1> About HTML </h1>
 <p>London is the capital city of England. It is the most populous city in the United Kingdom, with a metropolitan area of over 13 million inhabitants.Standing on the River Thames, London has been a major settlement for two millennia,its history going back to its founding by the Romans, who named it Londinium.
HyperText Markup Language, commonly abbreviated as HTML, is the standard markup language used to create web pages. Along with CSS, and JavaScript, HTML is a cornerstone technology used to create web pages,[1] as well as to create user interfaces for mobile and web applications. Web browsers can read HTML files and render them into visible or audible web pages. HTML describes the structure of a website semantically and, before the advent of Cascading Style Sheets (CSS), included cues for the presentation or appearance of the document (web page), making it a markup language, rather than a programming language.</p>
<h2> Benefits of HTML </h2>
<p>Further development under the auspices of the IETF was stalled by competing interests. Since 1996, the HTML specifications have been maintained, with input from commercial software vendors, by the World Wide Web Consortium (W3C). However, in 2000, HTML also became an international standard (ISO/IEC 15445:2000). HTML 4.01 was published in late 1999, with further errata published through 2001. In 2004, development began on HTML5 in the Web Hypertext Application Technology Working Group (WHATWG), which became a joint deliverable with the W3C in 2008, and completed and standardized on 28 October 2014.
In July 2012, WHATWG and W3C decided on a degree of separation. W3C will continue the HTML5 specification work, focusing on a single definitive standard, which is considered as a "snapshot" by WHATWG. The WHATWG organization will continue its work with HTML5 as a "Living Standard". The concept of a living standard is that it is never complete and is always being updated and improved. New features can be added but functionality will not be removed.
 </p>
 <!-- Adding Image-->
 <%= link_to image_tag('html.png') %>
 </td>
 </tr>
<!-- Footer Section-->
 <tr>
 <td style = "color : white"; colspan = "2" height= "20" align = "center" bgcolor="black"> Copyrights </td>
 </tr>
</table>
</body>
</html>

<%= link_to'About', about_path %>

app/views/alpha_blog/home.html.erb
<h1> This is Alpha blog </h1>
<%= link_to'About', about_path %> | 
<%= link_to 'Alpha-Blog', articles_path %>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2> Note Following Error Messages </h2>
<ul>
    <% @article.errors.full_messages.each do|msg| %>
    <li> <%=msg %></li>
    <%end%>
</ul>
<%end%>
<%= form_for @article do|f| %>
<p>
<%= f.label :title %><br/>
<%= f.text_field :title %>
</p>
<p>
    <%= f.label :description %></br>
    <%= f.text_area :description %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>
<%= link_to 'List Article', articles_path %>

app/views/articles/edit.html.erb
<h2> Edit existing article</h2>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1> Listing all articles</h1>
<p>
<%= link_to 'Create Article', new_article_path %>
</p>
<table>
    <tr>
        <th>Title</th>
        <th>Description</th>
    </tr>
    <% @articles.each do|art| %>
    <tr>
        <td><%= art.title %></td>
        <td><%= art.description %></td>
        <td><%= link_to 'Edit', edit_article_path(art) %></td>
        <td><%= link_to 'Show', article_path(art) %></td>
        <td><%= link_to 'Delete', article_path(art), method: :delete, data: {confirm: "Are you sure you want to delete(yes?)"}%> </td>
    </tr>
    <% end %>
</table>

app/views/articles/new.html.erb
<h1>Create an article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h3> Showing Selected Article</h3>
<p>
Title: <%= @article.title %>
</p>
<p>
Description: <%= @article.description %>
</p>
<%= link_to 'List Article', articles_path %> |
<%= link_to 'Edit this Article', edit_article_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlpaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name,msg| %>
<ul>
  <li>
    <%= msg %>
  </li>
</ul>
<% end %>
<%= yield %>

</body>
</html>